feat: update

diff --git a/install b/install
--- a/install
+++ b/install
@@ -41,21 +41,21 @@ set -o errexit -o errtrace -o pipefail -o nounset
 shopt -s expand_aliases     # This trick requires enabling aliases in Bash
 BASENAME="$(basename "$0")" # Complete file name
 echo_and_restore() {
-	echo "[${BASENAME}] $(cat -)"
-	# shellcheck disable=SC2154
-	case "$flags" in *x*) set -x ;; esac
+  echo "[${BASENAME}] $(cat -)"
+  # shellcheck disable=SC2154
+  case "$flags" in *x*) set -x ;; esac
 }
 alias log='({ flags="$-"; set +x; } 2>/dev/null; echo_and_restore) <<<'
 
 # Exit trap
 # This runs at the end or, thanks to 'errexit', upon any error
 on_exit() {
-	{
-		_RC="$?"
-		set +x
-	} 2>/dev/null
-	if ((_RC)); then log "ERROR ($_RC)"; else log "SUCCESS"; fi
-	log "#################### END ####################"
+  {
+    _RC="$?"
+    set +x
+  } 2>/dev/null
+  if ((_RC)); then log "ERROR ($_RC)"; else log "SUCCESS"; fi
+  log "#################### END ####################"
 }
 trap on_exit EXIT
 
@@ -63,8 +63,8 @@ log "==================== BEGIN ===================="
 
 # Help message (extracted from script headers)
 usage() {
-	grep '^#/' "$0" | cut --characters=4-
-	exit 0
+  grep '^#/' "$0" | cut --characters=4-
+  exit 0
 }
 REGEX='(^|\W)(-h|--help)($|\W)'
 
